### ISSUE TITLE
Maven submission?

### ISSUE THREAD

**Issue by power7714** [MostafaGazar/CustomShapeImageView#12]
Any plans to upload this to the Maven repository for easier way to include this library in an Android Studio project?

**Comment by MostafaGazar** [comment]
Working on that at the moment

**Comment by kibotu** [comment]
use jitpack for the time being:

https://jitpack.io/#MostafaGazar/CustomShapeImageView

**Comment by MostafaGazar** [comment]
Added to maven central: 
compile 'com.mostafagazar:customshapeimageview:1.0.4'
